### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by KarenEfereyan** [layer5io/meshery-nginx-sm#1]
@Chandra and @Lee how does this repo work

**Comment by kumarabd** [comment]
@KarenEfereyan  This repo does not have the actual adaptor code yet. This is just a template for @kushthedude  or anyone who is working on this adapter project to push changes to.

**Comment by leecalcote** [comment]
NGINX is releasing a new service mesh. Meshery will have an adapter for this service mesh.

**Comment by KarenEfereyan** [comment]
Thank you
