### ISSUE TITLE
docker image is >300 mb

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery-nginx-sm#16]
Fix the docker file to make image around 30 MB or so

**Comment by utkarsh-pro** [comment]
@kushthedude I brought down the image size to 130MB. I don't know if we can reduce it further as we are copying scripts directory in there which in itself is of around 35MB and the compiled binary is of around 40MB. Please let me know if I should create a PR with the modified Dockerfile.

**Comment by kushthedude** [comment]
Docker image should only have a compiled binary (~40 MB) + scripts directory (~2kb). About the scripts directory being 35mb, meshctl binary has been pushed accidentally, which we may ignore. Can you try to bring down to around ~40mb, I guess then we can go ahead with a PR and merge it.

**Comment by kushthedude** [comment]
@kumarabd meshctl binary is accidentally committed or do we need the binary for the adapter 🤔 ?

**Comment by utkarsh-pro** [comment]
> Docker image should only have a compiled binary (~40 MB) + scripts directory (~2kb). About the scripts directory being 35mb, meshctl binary has been pushed accidentally, which we may ignore. Can you try to bring down to around ~40mb, I guess then we can go ahead with a PR and merge it ?

@kushthedude I thought it is required as it was being used in the scripts under the script directory :sweat_smile:

**Comment by kushthedude** [comment]
> > Docker image should only have a compiled binary (~40 MB) + scripts directory (~2kb). About the scripts directory being 35mb, meshctl binary has been pushed accidentally, which we may ignore. Can you try to bring down to around ~40mb, I guess then we can go ahead with a PR and merge it ?
> 
> @kushthedude I thought it is required as it was being used in the scripts under the script directory 😅

@utkarsh-pro Please go ahead, the docker image size is ~1gb which needs to reduced immediately.

**Comment by utkarsh-pro** [comment]
> @utkarsh-pro Please go ahead, the docker image size is ~1gb which needs to reduced immediately.

@kushthedude actually the adapter is being rewritten using meshkit and meshery-adapter-library that's why the docker image size issue was stalled :sweat_smile:
